name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: False
          SHOW_TIMEZONE: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          IGNORED_REPOS: "git1,awesome-computer-vision,atlasreader,Stock-price-prediction-using-GAN,optimizers.numpy,bootstrap,Genetic-Algorithm-For-Training-Neural-Networks,awesome-computer-vision,Free-Courses-available-on-the-internet,ETHIndia,ipanditi.github.io,plots,AML,ML,Medical_Image_Processing,Facial-Expression-Detection,Clinical-Predictions,Data-Preprocessing,Complete-Python-3-Bootcamp,First-Language-Model,pandit_gpt,toon3-huddle01"
